---
galaxy_info:
  author: Yannick Sebastia
  description: Configure Dovecot
  license: GPL-3.0-only
  min_ansible_version: '2.1'
  namespace: sebastia
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
dependencies:
  - role: ysebastia.base.firewalld
    when: enable_service_dovecot
  - role: ysebastia.base.selinux
    when: enable_base_selinux
