---
- name: Install MariaDB
  become: true
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    update_cache: true
- name: Install BZIP2
  become: true
  ansible.builtin.apt:
    name:
      - bzip2
    update_cache: true
  when: enable_service_mariadb_cron
