---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos9s
    box: centos9s
    box_version: 20230207.0
  - name: debian11
    box: debian11
    box_version: 11.6.0-2
  - name: ubuntu2210
    box: generic/ubuntu2210
    box_version: 4.2.8
provisioner:
  name: ansible
verifier:
  name: ansible
